inherit_from: .rubocop_todo.yml

Lint/LiteralInInterpolation:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
